title: Interesting Patents
description: > # this means to ignore newlines until "baseurl:"
  This is a website, where I gather interesting and funny patent applications or patents.
permalink: ':title/'
baseurl: "/patents" # the subpath of your site, e.g. /blog
url: "http://patents.vadaru.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/vadaru #if your site has a twitter account, enter it here

# Author Settings
author: Frank Schwalb # add your name
author-img: frank.jpg # add your photo
about-author: I am a Professional Support Lawyer at HOFFMANN EITLE. Always hungry of finding interesting patents. # add description
social-twitter: vadaru # add your Twitter handle
social-facebook: frank.schwalb # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: frankschwalb # add your Linkedin handle
social-email: fschwalb@hoffmanneitle.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
